### ISSUE TITLE
Reported viewController is always nil

### ISSUE THREAD

**Issue by sclamage** [Lukas-Stuehrk/LeakFinder#2]
When you call ViewControllerObserverReporter -reportPossibleViewControllerLeak:, the viewController parameter is always nil. This is because you're passing viewController into it, which was set to nil right before you enter the dispatch_after() block. You probably meant to pass in weakViewController instead.

Or better yet, do something like this instead of testing weakViewController directly:

```
UIViewController *strongViewController = weakViewController;
if (strongViewController) { 
           [self.reporter reportPossibleViewControllerLeak:strongViewController];
}
```

This would work around a very unlikely, but possible, race condition where weakViewController exists when you test it in the 'if' statement, but gets dealloced from some other thread before you get a chance to do anything with it.

**Comment by Ehlster** [comment]
You are absolutely right. Thank you very much for reporting, I will provide a fix.

**Comment by Ehlster** [comment]
Should be fixed in version `0.2.1`.

**Comment by sclamage** [comment]
Thanks for the quick fix!

**Comment by Ehlster** [comment]
You're welcome! Thanks again for reporting and thanks for your detailed analysis. Helped a lot!
